### ISSUE TITLE
Investigate `failure` crate

### ISSUE THREAD

**Issue by jpeddicord** [amzn/askalono#11]
askalono uses a lot of `Box<Error>`. The `failure` crate has been making a buzz: https://github.com/withoutboats/failure

This is likely a good error management story for askalono. I haven't done any research into actually implementing this; it's likely not too difficult to do.

**Comment by davidbarsky** [comment]
Steve Klabnik and Ashley Williams made a good point on [Twitter](https://twitter.com/ag_dubs/status/958379170094026752). Libraries that use custom derive (like Failure or Structopt) allow people to have write super-declarative code, where it's feasible to define a struct or enum, add an annotation, and do your thing. It's really nice to not worry about imperative builders anymore!

**Comment by jpeddicord** [comment]
Done in PR #12, thanks!
