### ISSUE TITLE
Propose Logo

### ISSUE THREAD

**Issue by mirzazulfan** [amzn/askalono#29]
Hi @amzn .. I'm a graphic designer and an open source enthusiast. I would like to contribute to your awesome project by proposing logo design for it if you allow me. I'll be doing it as a gift for free to your awesome project.
Best regard.
Mirza zulfan

**Comment by jpeddicord** [comment]
Hi @mirzazulfan,

We're not looking for a logo right now; but thanks for the offer!

Jacob

**Comment by mirzazulfan** [comment]
Thanks for your response sir. Have a nice day.
