### ISSUE TITLE
Please include the license file into the askalono-cli crate

### ISSUE THREAD

**Issue by eclipseo** [amzn/askalono#38]
It would help for packaging.  Also the README and NOTICE included with the cli would help too.

**Comment by jpeddicord** [comment]
Ah! Good catch. This will probably be best served by a wrapper script to copy those into the CLI crate before publishing.

**Comment by ignatenkobrain** [comment]
it is much easier than that. Just create symlinks.

**Comment by jpeddicord** [comment]
Symlinks work if Cargo will dereference them when packaging. Does it?

Looking at https://github.com/rust-lang/cargo/issues/2748 it doesn't seem to have any good symlink behavior.

**Comment by jpeddicord** [comment]
I forgot to do this in 0.4.0 just now, but I see that at least today cargo _does_ deref symlinks! So I've added these in and will get that out in 0.4.1 (I intend on some faster release cadence, so hopefully real soon.)

**Comment by jpeddicord** [comment]
These were included in 0.4.1 as of last month. Thanks for reporting!
