### ISSUE TITLE
Is there any way to add license data?

### ISSUE THREAD

**Issue by soimsoim** [amzn/askalono#53]
This tool is really fast and nice. 
Is there any way to add license data?
Can this extracts the copyright text?

**Comment by jpeddicord** [comment]
Thanks!

>  Is there any way to add license data?

Sure is. If you're using the API: https://docs.rs/askalono/0.4.2/askalono/struct.Store.html#method.add_license

If you're using the command-line tool, it only knows how to load a dataset from the SPDX license-list-data repository:

```
Load an SPDX license directory (see https://github.com/spdx/license-list-data/tree/master/json/details for format)

USAGE:
    askalono cache load-spdx [FLAGS] <DIR>

FLAGS:
    -h, --help       Prints help information
        --store      Store texts in cache along with match data
    -V, --version    Prints version information

ARGS:
    <DIR>    JSON "details" directory
```

It _could_ learn to do more; I've just never quite prioritized that work myself. Open to options.

> Can this extracts the copyright text?

askalono does not know how to do this at the moment, but I see you asked about this in #54 -- let's scope that there.

**Comment by soimsoim** [comment]
Thank you for your kind answer. 
This question is solved so I closed this issue.

I look forward to the function for copyright text #54 .

Thanks and regards,
Soim
