### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by jpeddicord** [amzn/askalono#7]
- Basic compile check
- Upload artifacts to GitHub release

**Comment by Phrohdoh** [comment]
@teteros did a fantastic job setting up Travis and AppVeyor for [`easage`](https://github.com/Phrohdoh/easage/pull/17) (a tool for game modders).

Perhaps it can be used as a reference (unless of course you already know how you'll set this up in which case ignore this comment).

**Comment by jpeddicord** [comment]
@Phrohdoh I haven't looked into it at all; that's a wonderful reference. Thanks!

**Comment by jpeddicord** [comment]
Implemented for Travis CI. AppVeyor not yet done; tracking in #8.
