### ISSUE TITLE
AppVeyor

### ISSUE THREAD

**Issue by jpeddicord** [amzn/askalono#8]
Like #7, but Windows builds:

- Basic compile check
- Upload artifacts to GitHub release

**Comment by jpeddicord** [comment]
Oookay. So I spent some time and came up with https://github.com/amzn/askalono/blob/master/.appveyor.yml, however it's not quite functional:

- For reasons not worth digging into here, we can't use AppVeyor's own GitHub integration on this repo. This means that it's unable to detect when a push is a tag (release) or just a commit.
- It's possible to detect if a tag is present on a commit with `git describe --exact HEAD`. But I got lazy when I realized I'm terrible at Windows batch scripting.
- The YAML config is fixed at a static URL (master branch), so build changes in the future here will get... weird.

But it's a start.

**Comment by sschuberth** [comment]
If AppVeyor integration doe snot work for you for whatever reason, maybe using [Tea CI](https://docs.tea-ci.org/usage/overview/) is an option? In any case, @jpeddicord, let me know if I can help with Windows support.

**Comment by jpeddicord** [comment]
@sschuberth I'm not opposed to Tea CI, though if we can I'd like to shoot for a native Windows build (+MSVC) instead of Wine + Cygwin. Everything is still possible in AppVeyor, it's just that the above issues need to be tackled. (Alternatively, when appveyor/ci#1979 gets fixed, then we can go the usual OAuth/integration route.)

**Comment by jpeddicord** [comment]
AppVeyor uses a GitHub App now: https://www.appveyor.com/blog/2018/10/02/github-apps-integration/

This is all done and working (tested on a personal fork).
